#!/usr/bin/env php
<?php
/*
 * This file is part of Flarum.
 *
 * (c) Toby Zerner <4008353@qq.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require 'vendor/autoload.php';

$console = new Puzzle\Console\Console([
    'base'   => __DIR__,
    'public' => __DIR__ . '/public',
]);

$console->listen();
